version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/interchainio/tm-load-test
  docker:
    - image: circleci/golang

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/interchainio/tm-load-test/build
      - run:
          name: Release
          command: |
            /bin/bash .circleci/release.bash

workflows:
  version: 2

  mini_qa:
    jobs:
      - lint
      - test
      - build
  release_management:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
