# -------------------------------------------
# Installs Tendermint outage simulator server
# -------------------------------------------
- name: Copy binary to nodes
  copy:
    src: "{{ tm_outage_sim_server_bin }}"
    dest: /usr/bin/tm-outage-sim-server
    owner: root
    group: root
    mode: 0755
- name: Remove any old outage sim server files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/outage-sim-server.service
    - /usr/bin/outage-sim-server
- name: Copy service definition to nodes
  copy:
    src: config/tm-outage-sim-server.service
    dest: /etc/systemd/system/tm-outage-sim-server.service
- name: Reload systemd services
  systemd:
    daemon_reload: yes
